== 从战术说开去

=== 战术是什么

在网上待久了，
越发觉得很多词语的概念都被淡忘，被混淆。
本书中的战术一词指的是由单兵与小团体执行的，
在局部战场发挥优势的操作行为。

战术应该是随处可见的简单操作。
而不是高不可攀的奇技淫巧。
本书所讲述的战术都是从广大玩家的行为中总结而来。
普通玩家只要意识到战术的存在，
稍加练习就可以掌握基本的执行方法。
而知晓战术的存在，
则是玩家提升自身游戏水平所需要迈出的第一步。

战术是用来制造优势的。
优势可以是地图区域的控制权 -- 控制了对方的旗圈并达到足够长的时间就可以占旗获胜。
优势也可以是有利的血量交换比，以更少的代价消灭更多的敌人。

战术必须是具体的，可以执行的。
虽然人们谈到游戏中坦克的“打法“，总会使用肉搏，绕侧，黑枪等词汇，
或者使用“视野压制“，“保存血量“这种更高层次的词汇。
但这些“打法”都不是几句话能描述清楚的。
甚至于它们的定义也很难被明确地统一下来。
因此它们也就不在本书所探讨的战术概念范围之内。

=== 战术与战略

战术（tactics）与战略（strategy）是一对常被混淆的概念。
你可能会习惯性地把锡城上山一波流称作为“战术”。
而严格意义上来说，战术是个微观概念，
战略才是指整盘游戏的统筹计划。
这样来看，一波流应该是战略而非战术。
只不过战略这个词对于大众来说过于陌生，不被经常提及罢了。

好的战略应该能允许玩家在战略的不同阶段都有优势的战术可以使用。
这样才可以通过积累优势达到胜利的条件。

=== 战术与游戏机制

我们所玩的每一盘游戏都是在现有的游戏机制与数据所构成的框架之下，
输入了玩家的操作指令运行而成的一个实例。
战术则是在固有的游戏机制下尽可能地为自己争取优势的方法。
掌握了适合自己的战车的战术，
就能更多地发挥车辆的优势属性来制造优势。
这样你就可以自称“会玩”一辆车了。

=== 战术与玩家

玩家不仅需要尽量多地掌握战术，
还需要根据战场的实际情况与自己的战略目的选择合适的战术。
本书中介绍的战术有很多战术是可以不依赖车辆特征的。
掌握的战术越多，临场的选择就越多。

遗憾的是，
我无法保证你学会了书中的战术之后就能打到一定的效率值。
因为战术的实际选择与执行都是要靠你自己完成的。
而且你还会发现书中的很多战术都是非常简单基础的内容，
简单得简直不值得花时间写成书。
对于有了一定游戏经验的你来说读过了也是浪费时间。
这都是意料之内的事情。

=== 有关火炮

我自己玩火炮的经验很少，
因此这本书基本上和火炮没什么关系。
也许在未来的某个版本，
我会把这部分内容补充上。
又也许会因为我个人对敌方火炮的厌恶而放弃吧。
