== 换血

换血是一类简单的战术。
我们把需要消耗自身血量来打击对手的战术都归类为换血。

=== 单发换血

在确定会被对方攻击一次的情况下，
决定不规避这次攻击，坚持攻击对手一次，
就称作为单发换血。

由于坦克的单发伤害有所不同，
在单发换血时高伤害的坦克就会打掉比对方更多的血量。
从而获得优势。

一种特殊的情况是：对手的血量明显低于你的单发伤害，
即使考虑到伤害有 25% 的上下浮动，依然可以有把握一发将对手击毁。
那么这时即使你的单发伤害低于对手，也可以考虑采用单发换血战术。
毕竟死人是没有输出能力的，
击毁一辆坦克所带来的优势很大。

单发伤害的英文为 Damage per Hit，可以缩写做 DPH。
但社区中更为流行的另一种简单的称谓是 alpha。

=== N 换 1 换血

由于坦克的装填时间不同，
在单发换血之后可能会有一方提前完成装填。
这一方就可以在对方装填好之前再发动一次甚至多次攻击。
最常见的状况是承受一次攻击而攻击对方两次，亦即 2 换 1。

需要指出的是，
坦克的移动，瞄准，以及玩家自身的操作与反应都需要耗费时间。
双方开炮也必然有先后之分，
因此如果交战双方的装填时间差别不大，
装填稍快的一方很可能并不容易打出 2 换 1 的效果，
而只能止步于单发换血。

=== DPM 换血

在确定会被对方持续攻击的情况下，
决定不规避对方的火力，持续攻击直到对方被击毁为止，
这种战术称为 DPM 换血。

DPM 的全称是 Damage per Minute，意既每分钟可以造成的伤害。
虽然在其他游戏中更为常见的同类概念是 DPS（Damage per Second），
但坦克世界的游戏节奏相对较慢，因此使用一分钟作为单位时间更为直观。

DPM 的计算方式在社区中极为不统一。
最简单的计算方式是 DPH 乘以射速。
而射速一项会受到成员技能与坦克配件的影响。
再者，由于双方交战时的第一发炮弹是事先已经装填好的，
因此也有人在计算 DPM 时会在前面的数值基础上再加上 DPH。
这里我无法确定一个“最好”的 DPM 算法。
我只能提醒你：DPM 的算法在不同人手里会有所出入，
阅读他人的观点时要有所留意。

与单发换血和 N 换 1 换血不同的是，
DPM 换血的目的通常是将对手击毁。
而不是简单地打出一个“回合”的优势。

=== 弹夹换血

由于弹夹车的短装填时间很短，
与单发车换血时往往能打出很大的优势。

基于双方的装填时间不同，
你需要选择主动承受对方一次，两次，甚至更多次的攻击。

弹夹换血的通常目的是击毁目标。
因此你在使用这一战术之前，
需要观察自己弹夹的剩余伤害能力以及对手的剩余血量，
以及自己可能因为种种原因未能击中/未能击穿对手，
并且考虑到队友跟进偷炮所造成的伤害，
再决定是否要换血。

弹夹换血与 N 换 1 非常相似，
都要依赖自身装填时间的优势来打出优势的伤害。
不同之处在于弹夹换血可能承受对手多于一次的反击，
而且弹夹一般都以击毁目标为目的。
从这个角度来看弹夹换血又与 DPM 换血有相似之处。

=== 换血与强吃

“强吃”是一个已经在坦克世界玩家群体中耳熟能详的概念。
联系到本书中的换血战术概念，
强吃相当于 DPM 换血。

DPM 换血是否一定优于单发换血 / N换1 ？
这里我的想法是：单发换血 / N换1 这两者换血战术在对手已经无路可退的情况下，
依然可以满足进攻方维持自己的有效 DPM 来持续输出。
如果没有队友的支援，DPM 换血并不能更快地击杀目标。

=== 换血的条件

读过前面几种换血战术之后，
想必你自己也能看出：
熟悉敌我双方的单发伤害与装填时间，
可以帮你选择合适的换血战术。

换血需要花费自己的血量来打掉对手的血量。
这意味着你自身剩余的血量决定了你可以承受几次对手的攻击。
进而可以使用几次换血战术。
如果可以的话，最好还能考虑一下换血之后的局面。

换血要求你能够可靠地击中并击穿对手。
一次未击中/未击穿不仅会造成临时的血量劣势，
更容易带来心理上的焦虑，使你接下来的心理状态变差。
这就要求你对装甲模型与击穿机制有熟练的掌握。

一般来说，
换血战术只探讨一对一交战的情况。
在敌方多人火力打击之下，
攻击对手一次的代价是承受一轮火力。
除非能击毁敌方的重要坦克，
否则这等于是在为敌方制造优势。

如果换血之后不能击毁对手，
那么你需要撤退到队友的掩护范围内，
并且有安全的掩体可用。
例如，你选择了单发换血战术，
但身后缺少支援火力，
那么对手就可以从容地追上来再度攻击你，
这就演变成对方采用了 2 换 1 换血，或者 DPM 换血。
局部形势可能就会逆转。
