== 准备知识

本着“理论指导实践”的原则，
我们先来看看游戏自身的机制与数据，
亦即“游戏规则”。
也许你从其他一些攻略心得中学到了零散的游戏机制，
但我在这里需要把我自己熟悉的数据来源分享出来，
确保我们能站在同一起平台上对话，
而不是抱着不同的字典来互相误解。

这一章所提到的所有信息来源都可以在本书<<_附录>>中找到网址。

=== 游戏机制

游戏机制是指游戏内发生的所有事件的计算与判定方法。
战术则是游戏机制的直接利用与具体体现。
每学习一个战术，
都需要你对相应的游戏机制有充分的理解与掌握。

很多玩家本着悠闲游戏的态度，
并不会在开始游戏时就认真地去学习游戏机制。
对游戏机制的理解也仅停留在偶尔零星接触的道听途说上面。
没有辨识自己听说到的游戏机制是否正确的方案。
也无法跟随游戏机制的更新来提升自己对游戏的认识
（虽然游戏机制的更新并不频繁）。

目前 Wargaming 披露游戏机制的主要渠道包括官方论坛，
官方网站与link:{url-wg-youtube}[官方 YouTube 频道]。
{url-wg-wiki}[官方 wiki] 的内容基本都是由玩家将各处官方资讯归纳总结而成。

游戏机制的变动会在每个补丁的更新日志里写出。
官方网站保存了每个历史版本的link:{url-release-notes}[更新日志]。
官方 wiki 上面也同样保存了一份link:{url-wiki-release-notes}[副本]。

需要注意的是，每个版本上线之前，
超测服务器和测试服务器上都会泄漏 / 提前放出一份测试版的更新日志。
但最终正式上线的版本可能与之有所不同。
你在某些游戏资讯站点看到的更新日志也可能是过时的测试服务器上的版本。

=== 游戏数据

如果说游戏机制是数学公式，
那么游戏数据就是代入这个公式的各项参数。

目前玩家能访问到的游戏数据，
大多来自于游戏客户端自带的数据文件。
由于这些数据文件多为 XML 格式，
因此有些地方也用 XML 文件来指代这些数据文件。
理论上 Wargaming
完全可以在客户端里放一份与服务器端不同的、虚假的数据文件。
但我们这里选择相信 Wargaming 不会那么做。

客户端 XML 数据里并不包含所有的数据。
有些数据确实只有服务器才知道。
这部分数据就需要通过玩家进行黑盒实验来探索。
当你在网上遇到这些数据时，
由于一般玩家未必具有实验科学的必备素质，
最好不要轻易相信土法实验所得出的数据。

目前在 PC 上最好的游戏数据查看软件是link:{url-tank-inspector}[装甲密档]。
如果你更喜欢使用移动设备。
安卓系统上的link:{url-android-kb-play}[坦克世界知识库]也是个不错的选择。

=== 地图知识

每一盘游戏都离不开一张具体的地图。
本书中也会用到具体的地图点位来作为战术应用的举例。
考虑到每个版本都可能做出地图的修改，
我会在举例时注明所使用的地图版本。

你不必立即去收集各个地图的高清 / 等高缩略图。
每当你学会了新的战术动作，
了解了战术所需要的特定地形，
未来你在战斗 / 跑图时就会主动去留意相类似的、可以利用的地形。
