== 侦察

在前一章狙击里我们提到了有些狙击战术需要依赖队友来点亮敌人。
那么这一章我们就来谈谈侦察的基本技术。

=== 超视野点亮

如果你能在被敌方车辆点亮之前先手将敌方点亮，
并且维持着双方的相对距离。
不至于因为距离太近导致自己被点亮，
也不至于因为距离太远而导致敌方消失。
这种技术动作我们称其为超视野点亮。

社区中对这种点亮技术还有不同的称呼。
由于这种技术完全依赖敌我双方点亮距离的差距，
不依赖草丛提供的隐蔽，
因此也可以叫做“视野风筝（Vision Kiting）”，
或者“平地点亮”，“平地静默”。

这一战术要求地图有足够大的开阔地区，
可以让双方在不受草丛 / 掩体遮挡的条件下交战。

=== 反斜面点亮

在坡顶探头点亮敌方，
随后退回到反斜面来规避敌方直射火力。
等待自身车辆灭点之后重复以上动作。
这一技术我们称作为反斜面点亮。

反斜面点亮主要用于敌方车辆享受草丛提供的隐蔽，
需要拉近距离才有可能成功点亮的情形。
这种情况下主动侦察的一方无法使用超视野点亮，
只能依赖斜坡作为掩体来拉近双方距离。
并且同时依赖斜坡来保证侦察车的自身安全。

值得注意的是，
因为侦察车在使用斜坡反斜面点亮敌人，
那么被点亮的敌方车辆对于己方的支援火力而言可能也在反斜面之后。
这样己方的直射火力未必能提供支援到，
只能依赖火炮支援。
如果能从侧翼点亮对手就不存在这一问题。

=== 草后静默

草丛可以提供相当高的隐蔽系数。
而处于车辆 15 米范围内的草丛不会为敌方车辆提供隐蔽。
将自己的车辆驶入草丛 15 米范围内，
并保持草丛始终遮挡着敌方车辆的视线，
这种技术我们称其为草后静默。

草后静默的主要适用场景与超视野点亮类似，
都适用于点亮大片开阔地上可能出现的敌人。
但由于侦察车使用草丛为自己提供隐蔽，
在敌人试图肉侦冲锋的时候会有余裕的时间和空间，
等待队友的狙击火力将敌人消灭。

但是话说回来，
如果草丛的位置恰好在敌方进攻的路线上，
亦即，敌人在被点亮时会逐渐接近侦察车，
当距离拉近到一定程度时最终是会点亮侦察车的。
很多经典的草后静默位置都是在敌人行军路线的侧翼点亮。
安全性就会高很多。

由于草丛可以提供的隐蔽很高，
很多车辆（不只是轻坦）都可以胜任草后静默的工作。
另玩家深恶痛绝的多台 TD 在大片草丛内深蹲，
其实就是蹲在前面的敌人在做草后静默。

=== 侦察与配件

有很多配件可以影响车辆的视野与隐蔽，
从而影响着侦察战术的执行。

==== 炮队镜

炮队镜在车体静止达 3 秒后可以提供 25% 的视野加成，
对视野提升非常之高。
而且由于炮队镜可以免费拆卸，
往往是新上手侦察车的玩家们首先会考虑的配件。
不过我们从战术应用的角度来看，
炮队镜似乎没有那么美好。

最适合使用炮队镜的战术是自然是草后静默。
如果侦察车对自己的隐蔽值知根知底，
而且大致可以确定敌方车辆没有掩体 / 草丛的防护，
那么超视野点亮也有可能发挥炮队镜的作用。
反斜面点亮无法使用到炮队镜。
但反斜面点亮也是瓦解蹲坑 TD 的重要技术（甚至可能是唯一有效且安全的技术）。
因此，炮队镜的意义在我个人心目中大打折扣。

==== 高级光学观察镜

一般简称“高光”。
可以在任意时刻提供 10% 的视野加成，但不与炮队镜相叠加。
高光可以为所有的侦察技术所服务。
而且高光没有重量，不会降低使用者的推重比（从而影响机动性）。
凡是有意自主侦察的车都推荐装高光。

高光的缺陷在于对视野的加成只有 10%。
安装在基础视野较差的车辆身上效果不佳。
在中低级车辆上这一问题尤为明显。
但实际的地图尺寸、交战距离却不会改变 --
或者通俗地说，
3 级车能进入的普罗霍洛夫卡与 10 级车进入的普罗霍洛夫卡都是那么大。
如果说 10 级车普遍地拥有 400 米基础视野，
带上高光就可以基本满足需求；
低级车就不得不依赖炮队镜来把视野撑上去。

==== 伪装网

伪装网在车体静止 3 秒后为车辆提供一定的隐蔽加成。
具体的数值与车辆类型相挂钩。
TD 最多，LT 与 MT 次之，MT 与 SPG 最少。

伪装网与炮队镜一样可以免费拆卸。
也很受新人玩家的欢迎。
不过在我个人看来，
伪装网在侦察方面的意义比炮队镜更小。
下面就是具体的分析。

首先很明显：反斜面点亮无法发挥伪装网的作用。
草后静默战术是伪装网较为有用的情形，
但仅限于敌方肉侦接近时才有意义。
如果距离不够近，草丛提供的隐蔽往往已经很够用。

接下来我们来看超视野点亮：
如果我们需要伪装网生效，才可以足够地接近并点亮敌人，
那么在伪装网生效前的 3 秒时间内，
侦察车的隐蔽值是不够用的，这时侦察车就已经被对方点亮了。
虽然接下来侦察车可以借助伪装网“平地灭点”，
但恐怕此时对方的狙击火力早已经开始开火。
这样来看，
超视野点亮技术也无法有效利用伪装网的效果。

==== 通风

通风可以提升车长的熟练度，间接提升视野。
同时通风还可以提升已经学习了隐蔽技能的成员的隐蔽技能值，
进而提升实际的车辆隐蔽值。
但由于通风对车辆属性的实际影响太小，
很难起到量变到质变的作用。
这里我们也就不再展开讨论。
